/**
 * Baseline security response headers for this app (§25 / production CSP).
 *
 * Kept as plain string constants so the same policy can be:
 * - written into `public/_headers` (Cloudflare Workers Assets),
 * - asserted by contract tests,
 * - attached to API JSON responses that bypass the asset worker.
 *
 * CSP notes (honest, not aspirational):
 * - Fonts/scripts/styles are self-hosted via Next/`next/font` + vinext build
 *   output under `/_next/static/` — no third-party CDNs are required at runtime.
 * - `style-src 'unsafe-inline'` is required because the current CSS pipeline
 *   emits inline style attributes (e.g. frequency bar widths) and Tailwind
 *   runtime style injection in some paths.
 * - `script-src` allows `'self'` only in the baseline; if a future vinext/Next
 *   build injects inline boot scripts that break under this policy, tighten
 *   via hashes/nonces rather than silently adding `'unsafe-inline'` for scripts.
 * - `connect-src 'self'` covers same-origin `/api/*` and `/data/*` fetches only;
 *   the browser never talks to vietlott.vn directly (Worker does).
 */

export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "img-src 'self' data:",
  "font-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "script-src 'self'",
  "connect-src 'self'",
].join("; ");

export const SECURITY_HEADERS: ReadonlyArray<readonly [string, string]> = [
  ["Content-Security-Policy", CONTENT_SECURITY_POLICY],
  ["X-Content-Type-Options", "nosniff"],
  ["X-Frame-Options", "DENY"],
  ["Referrer-Policy", "strict-origin-when-cross-origin"],
  ["Permissions-Policy", "camera=(), microphone=(), geolocation=()"],
];

/** Cloudflare Workers Assets `_headers` body for `/*` (plus a cache rule for hashed assets). */
export function formatCloudflareHeadersFile(): string {
  const securityBlock = SECURITY_HEADERS.map(([name, value]) => `  ${name}: ${value}`).join("\n");
  return [
    "# Security baseline — source of truth: lib/security/headers.ts",
    "# Regenerated by scripts/write-security-headers.mjs (also run from npm run build).",
    "/*",
    securityBlock,
    "",
    "# Cache content-hashed assets immutably (also emitted by vinext; kept here so a",
    "# full rewrite of this file never drops the cache rule).",
    "/_next/static/*",
    "  Cache-Control: public, max-age=31536000, immutable",
    "",
  ].join("\n");
}

/** Attach security headers onto an existing Headers / plain object for API routes. */
export function applySecurityHeaders(headers: Headers): Headers {
  for (const [name, value] of SECURITY_HEADERS) {
    headers.set(name, value);
  }
  return headers;
}
